//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDiaChi : DbContext
    {
        public dbDiaChi()
            : base("name=dbDiaChi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbHuyen_> tbHuyen_ { get; set; }
        public virtual DbSet<tbTinh_> tbTinh_ { get; set; }
        public virtual DbSet<tbXa_> tbXa_ { get; set; }
    }
}
