//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQLKho : DbContext
    {
        public dbQLKho()
            : base("name=dbQLKho")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<tbCT_PhieuNhap> tbCT_PhieuNhap { get; set; }
        public virtual DbSet<tbCT_PhieuXuat> tbCT_PhieuXuat { get; set; }
        public virtual DbSet<tbHangHoa> tbHangHoas { get; set; }
        public virtual DbSet<tbLoaiHangHoa> tbLoaiHangHoas { get; set; }
        public virtual DbSet<tbNhaPhanPhoi> tbNhaPhanPhois { get; set; }
        public virtual DbSet<tbNhaSanXuat> tbNhaSanXuats { get; set; }
        public virtual DbSet<tbPhieuNhap> tbPhieuNhaps { get; set; }
        public virtual DbSet<tbPhieuXuat> tbPhieuXuats { get; set; }
        public virtual DbSet<tbTaiKhoan> tbTaiKhoans { get; set; }
    }
}
