//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHuyen_
    {
        public int MaHuyen { get; set; }
        public string TenHuyen { get; set; }
        public string LoaiHuyen { get; set; }
        public string ToaDo { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public int ViTri { get; set; }
    }
}
