//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhaSanXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbNhaSanXuat()
        {
            this.tbPhieuNhaps = new HashSet<tbPhieuNhap>();
        }
    
        public int producerId { get; set; }
        public string producerName { get; set; }
        public string producerAddress { get; set; }
        public Nullable<int> producerTown { get; set; }
        public string producerNumberPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuNhap> tbPhieuNhaps { get; set; }
    }
}
