//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhaPhanPhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbNhaPhanPhoi()
        {
            this.tbPhieuXuats = new HashSet<tbPhieuXuat>();
        }
    
        public int distributorId { get; set; }
        public string distributorName { get; set; }
        public string distributorAddress { get; set; }
        public Nullable<int> distributonTown { get; set; }
        public string distributonNumberPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuXuat> tbPhieuXuats { get; set; }
    }
}
