//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhieuXuat()
        {
            this.tbCT_PhieuXuat = new HashSet<tbCT_PhieuXuat>();
        }
    
        public int opBillId { get; set; }
        public Nullable<int> priceTotal { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<int> distributorId { get; set; }
        public Nullable<System.DateTime> whatDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCT_PhieuXuat> tbCT_PhieuXuat { get; set; }
        public virtual tbNhaPhanPhoi tbNhaPhanPhoi { get; set; }
        public virtual tbTaiKhoan tbTaiKhoan { get; set; }
    }
}
