//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhieuNhap()
        {
            this.tbCT_PhieuNhap = new HashSet<tbCT_PhieuNhap>();
        }
    
        public int ipBillId { get; set; }
        public Nullable<int> priceTotal { get; set; }
        public Nullable<int> producerId { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<System.DateTime> whatDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCT_PhieuNhap> tbCT_PhieuNhap { get; set; }
        public virtual tbNhaSanXuat tbNhaSanXuat { get; set; }
        public virtual tbTaiKhoan tbTaiKhoan { get; set; }
    }
}
