//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTaiKhoan()
        {
            this.tbPhieuNhaps = new HashSet<tbPhieuNhap>();
            this.tbPhieuXuats = new HashSet<tbPhieuXuat>();
        }
    
        public string accountName { get; set; }
        public Nullable<System.DateTime> accountDate { get; set; }
        public string accountSex { get; set; }
        public Nullable<int> accountHometown { get; set; }
        public string accountNumberPhone { get; set; }
        public string accountAddress { get; set; }
        public Nullable<int> accountTown { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string accountImage { get; set; }
        public int accountId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuNhap> tbPhieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuXuat> tbPhieuXuats { get; set; }
    }
}
