//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTinh_
    {
        public int MaTinh { get; set; }
        public string TenTinh { get; set; }
        public string LoaiTinh { get; set; }
        public int ViTri { get; set; }
    }
}
